HGHSD-206 Stable Config
labdao/api.labdao.xyz pull request #2
Opened 2022-12-22 22:56 UTC by victorbordo

### Summary
Create a slightly better configuration story across 
development and production. This includes modifications
to the application configuration and `ormconfig.ts` so
migrations can be run with the datasource locally and
in the continuous deployment pipeline.

### Test plan
1. Verify devs can run migrations locally:

```
$ yarn migration:run
```

2. Test deployment flow migration step runs successfully.

2022-12-22 22:59 UTC, victorbordo commented on .github/workflows/pipeline.yml
> +      - "**/staging/**"
Will use as a simple staging deployment with `main` a stable prod in case rollbacks are required.

2022-12-23 22:50 UTC, jlevers requested changes
mostly just some questions about what's going on :)

2022-12-23 22:50 UTC, jlevers commented on src/app.module.ts
> +      ignoreEnvFile: ignoreEnvFile,
how does this work on local? like how do the env vars get loaded? i know on GCP they get loaded into `process.env` sometime during the deploy but that doesn't happen when developing locally

2022-12-23 22:50 UTC, jlevers commented on .github/workflows/pipeline.yml
> +      - "**/staging/**"
does GCP somehow know automatically to deploy this to a different URL than prod?

2022-12-23 22:50 UTC, jlevers commented on src/app.module.ts
> +      ignoreEnvFile: ignoreEnvFile,
nvm i see

2022-12-23 22:50 UTC, jlevers commented on src/config/ormconfig.ts
> +  entitiesPath = '/../**/*.entity.{js,ts}';
in this case do we even need the `.js` files? or would just `.ts` be sufficient

2022-12-23 22:50 UTC, jlevers commented on src/repl.ts
> +import { repl } from '@nestjs/core';
is there a nest repl? sick

2022-12-23 22:53 UTC, victorbordo commented on .github/workflows/pipeline.yml
> +      - "**/staging/**"
GitHub actions [workflow syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore) is what you're looking for. Just manually create a staging branch and test the deployment. Eventually we can set up a staging environment if necessary but doesn't need to happen now imo.

2022-12-23 22:55 UTC, victorbordo commented on src/repl.ts
> +import { repl } from '@nestjs/core';
Yes see the recipe in [docs](https://docs.nestjs.com/recipes/repl). Used it for debugging. Worth keeping around.

2022-12-23 22:57 UTC, victorbordo commented on src/config/ormconfig.ts
> +  entitiesPath = '/../**/*.entity.{js,ts}';
I believe we want both.

2022-12-23 23:00 UTC, merged