add onboarded boolean to users
labdao/api.labdao.xyz pull request #4
Opened 2023-01-23 00:49 UTC by cwest144

- default false, switch to true when creating a project for a user.

2023-01-23 18:11 UTC, jlevers requested changes
couple minor things, but looks good overall :) call him mr. nestjs

once the couple little things are resolved you can merge

2023-01-23 18:11 UTC, jlevers commented on src/migrations/1674252381160-AddOnboardedToUsers.ts
> +    name = 'sh1674252381160'
let's rename this to `AddOnboardedToUsers1674252381160`. in the future, you can control the name by doing something like `yarn migration:generate AddOnboardedToUsers`

2023-01-23 18:11 UTC, jlevers commented on src/projects/projects.service.ts
> +    this.usersService.update(user.id, {onboarded: true});
this is my bad for not being clearer on slack, but this needs an `await` in front of it

2023-01-24 01:54 UTC, cwest144 commented on src/migrations/1674252381160-AddOnboardedToUsers.ts
> +    name = 'sh1674252381160'
the filename is currently matching the existing migrations

2023-01-24 01:57 UTC, merged